-- begin AUTODEALER_COUNTRY
create unique index IDX_AUTODEALER_COUNTRY_UNIQ_NAME on AUTODEALER_COUNTRY (NAME) ^
create unique index IDX_AUTODEALER_COUNTRY_UNIQ_CODE on AUTODEALER_COUNTRY (CODE) ^
-- end AUTODEALER_COUNTRY
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_COUNTRY foreign key (COUNTRY_ID) references AUTODEALER_COUNTRY(ID)^
create index IDX_SEC_USER_ON_COUNTRY on SEC_USER (COUNTRY_ID)^
-- end SEC_USER
-- begin AUTODEALER_MANUFACTURER
alter table AUTODEALER_MANUFACTURER add constraint FK_AUTODEALER_MANUFACTURER_ON_COUNTRY foreign key (COUNTRY_ID) references AUTODEALER_COUNTRY(ID)^
create unique index IDX_AUTODEALER_MANUFACTURER_UNIQ_NAME on AUTODEALER_MANUFACTURER (NAME) ^
create unique index IDX_AUTODEALER_MANUFACTURER_UNIQ_CODE on AUTODEALER_MANUFACTURER (CODE) ^
create index IDX_AUTODEALER_MANUFACTURER_ON_COUNTRY on AUTODEALER_MANUFACTURER (COUNTRY_ID)^
-- end AUTODEALER_MANUFACTURER
-- begin AUTODEALER_COLOUR
create unique index IDX_AUTODEALER_COLOUR_UNIQ_CODE on AUTODEALER_COLOUR (CODE) ^
create unique index IDX_AUTODEALER_COLOUR_UNIQ_NAME on AUTODEALER_COLOUR (NAME) ^
-- end AUTODEALER_COLOUR
